-- ============================================
-- 1. 系统用户表
-- ============================================
CREATE TABLE IF NOT EXISTS sys_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    nickname      VARCHAR(50)  NOT NULL,
    email         VARCHAR(254),
    phone         VARCHAR(20),
    avatar_url    VARCHAR(500),
    status        SMALLINT    NOT NULL DEFAULT 1,
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_user_username UNIQUE (username),
    CONSTRAINT ck_sys_user_status CHECK (status IN (0, 1))
    );

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_email
    ON sys_user (LOWER(email))
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_sys_user_phone
    ON sys_user (phone)
    WHERE phone IS NOT NULL;

COMMENT ON TABLE sys_user IS '系统用户';
COMMENT ON COLUMN sys_user.status IS '状态：0-禁用，1-正常';

-- 初始化管理员账号（密码为 admin，BCrypt 加密）
INSERT INTO sys_user (username, password_hash, nickname, status)
VALUES ('admin', '$2a$12$gjgi0yYUAY.7MRj.1Pbg7.bo2pfPQ6oqClCTB7xZ62qvBwFvWyFEC', '系统管理员', 1)
    ON CONFLICT (username) DO NOTHING;


-- ============================================
-- 2. AI 聊天会话表
-- ============================================
CREATE TABLE IF NOT EXISTS ai_chat_conversation (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    title      VARCHAR(100) NOT NULL DEFAULT '新聊天',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_chat_conversation_user
    FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_ai_chat_conversation_user_updated
    ON ai_chat_conversation (user_id, updated_at DESC, id DESC);

COMMENT ON TABLE ai_chat_conversation IS 'AI 聊天会话';


-- ============================================
-- 3. AI 聊天消息表
-- ============================================
CREATE TABLE IF NOT EXISTS ai_chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    conversation_id BIGINT      NOT NULL,
    role            VARCHAR(16) NOT NULL,
    content         TEXT        NOT NULL,
    created_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_chat_message_user
    FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_chat_message_conversation
    FOREIGN KEY (conversation_id) REFERENCES ai_chat_conversation (id) ON DELETE CASCADE,
    CONSTRAINT ck_ai_chat_message_role
    CHECK (role IN ('user', 'assistant'))
    );

COMMENT ON TABLE ai_chat_message IS 'AI 聊天消息记录';
COMMENT ON COLUMN ai_chat_message.role IS '消息角色：user-用户，assistant-AI';


-- ============================================
-- 4. 兼容旧数据迁移（若已存在旧版消息表）
--    将没有 conversation_id 的旧消息归入每个用户的“历史聊天”
-- ============================================
ALTER TABLE ai_chat_message
    ADD COLUMN IF NOT EXISTS conversation_id BIGINT;

-- 为每个用户创建一条“历史聊天”会话
INSERT INTO ai_chat_conversation (user_id, title, created_at, updated_at)
SELECT user_id,
       '历史聊天',
       MIN(created_at),
       MAX(created_at)
FROM ai_chat_message
WHERE conversation_id IS NULL
GROUP BY user_id;

-- 将旧消息关联到对应的“历史聊天”会话
WITH first_conversation AS (
    SELECT DISTINCT ON (user_id) user_id, id
FROM ai_chat_conversation
ORDER BY user_id, created_at, id
    )
UPDATE ai_chat_message message
SET conversation_id = conversation.id
    FROM first_conversation conversation
WHERE message.user_id = conversation.user_id
  AND message.conversation_id IS NULL;

-- 添加外键约束（若不存在）
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_ai_chat_message_conversation'
          AND conrelid = 'ai_chat_message'::regclass
    ) THEN
ALTER TABLE ai_chat_message
    ADD CONSTRAINT fk_ai_chat_message_conversation
        FOREIGN KEY (conversation_id)
            REFERENCES ai_chat_conversation (id)
            ON DELETE CASCADE;
END IF;
END $$;

-- 设置 conversation_id 非空
ALTER TABLE ai_chat_message
    ALTER COLUMN conversation_id SET NOT NULL;


-- ============================================
-- 5. 消息表索引
-- ============================================
CREATE INDEX IF NOT EXISTS idx_ai_chat_message_user_id_id
    ON ai_chat_message (user_id, id DESC);

CREATE INDEX IF NOT EXISTS idx_ai_chat_message_conversation_id_id
    ON ai_chat_message (conversation_id, id);