// Share-conversation dialog (Doubao-style): pick which messages to include,
// then copy a public link, copy them as text, or export a clean image. The
// link uploads the selected snapshot to franklin.run/api/share and copies the
// returned https://franklin.run/s/<id> URL.

import { useMemo, useRef, useState } from "react";
import { toPng } from "html-to-image";
import { Check, Copy, ImageDown, Link2, X, ChevronDown } from "lucide-react";
import type { ChatMessage } from "../hooks/use-franklin-chat";
import { MessageContent } from "./MessageContent";
import { iconFor } from "./ToolGroup";
import { copyText } from "../lib/clipboard";
import { useTryLang } from "../lib/i18n";

// Image-share message cap (Doubao-style). A very tall PNG hits browser canvas
// size limits and degrades; over this many selected bubbles we disable "share
// image" (the link has no such limit, so it stays available).
const IMAGE_SHARE_LIMIT = 30;

const LABELS: Record<string, {
  title: string; cancel: string; all: string; copy: string; copied: string; img: string; busy: string;
  link: string; linking: string; linked: string; linkErr: string;
  previewTitle: string; copyImg: string; copiedImg: string; copyImgFail: string; download: string; heading: string; disclaimer: string;
  imgLimit: (n: number) => string;
}> = {
  en: {
    title: "Select messages", cancel: "Cancel", all: "Select all", copy: "Copy", copied: "Copied", img: "Share image", busy: "Rendering…",
    link: "Copy link", linking: "Creating…", linked: "Link copied", linkErr: "Share failed",
    previewTitle: "Image preview", copyImg: "Copy image", copiedImg: "Copied", copyImgFail: "Copy failed", download: "Download image", heading: "Shared conversation", disclaimer: "Generated by AI · may not be fully accurate",
    imgLimit: (n) => `Over ${n} messages selected — can't share as image`,
  },
  zh: {
    title: "选择对话", cancel: "取消", all: "全选", copy: "复制", copied: "已复制", img: "分享图片", busy: "生成中…",
    link: "复制链接", linking: "生成中…", linked: "链接已复制", linkErr: "分享失败",
    previewTitle: "分享图片预览", copyImg: "复制图片", copiedImg: "已复制", copyImgFail: "复制失败", download: "下载图片", heading: "分享对话", disclaimer: "内容由 AI 生成,不能完全保障真实",
    imgLimit: (n) => `所选对话超过 ${n} 条,无法分享图片`,
  },
  es: {
    title: "Seleccionar mensajes", cancel: "Cancelar", all: "Todos", copy: "Copiar", copied: "Copiado", img: "Compartir imagen", busy: "Generando…",
    link: "Copiar enlace", linking: "Creando…", linked: "Enlace copiado", linkErr: "Error al compartir",
    previewTitle: "Vista previa", copyImg: "Copiar imagen", copiedImg: "Copiado", copyImgFail: "Error al copiar", download: "Descargar imagen", heading: "Conversación compartida", disclaimer: "Generado por IA · puede no ser exacto",
    imgLimit: (n) => `Más de ${n} mensajes seleccionados — no se puede compartir como imagen`,
  },
};

// Localized "2026 年 6 月 3 日" / "June 3, 2026" date for the image header.
function fmtDate(lang: string): string {
  const d = new Date();
  if (lang === "zh") return `${d.getFullYear()} 年 ${d.getMonth() + 1} 月 ${d.getDate()} 日`;
  try {
    return d.toLocaleDateString(lang === "es" ? "es-ES" : "en-US", { year: "numeric", month: "long", day: "numeric" });
  } catch {
    return d.toDateString();
  }
}

// Where the public share snapshot is published. The desktop talks to the
// deployed Franklin web app; override for staging via window.__FRANKLIN__.
const SHARE_API =
  (typeof window !== "undefined" && (window as { __FRANKLIN__?: { shareApi?: string } }).__FRANKLIN__?.shareApi) ||
  "https://franklin.run/api/share";

function mediaTag(m: ChatMessage): string {
  if (m.kind === "image") return "[image]";
  if (m.kind === "video") return "[video]";
  if (m.kind === "music") return "[audio]";
  return "";
}

export function ShareDialog({ messages, onClose }: { messages: ChatMessage[]; onClose: () => void }) {
  const { lang, t } = useTryLang();
  const L = LABELS[lang] ?? LABELS.en;

  // Shareable items: text + media bubbles (skip tool-activity segments).
  const items = useMemo(
    () => messages.map((m, i) => ({ m, i })).filter((x) => x.m.kind !== "tools" && (x.m.content || x.m.image || x.m.video || x.m.music)),
    [messages],
  );
  const [sel, setSel] = useState<Set<number>>(() => new Set(items.map((x) => x.i)));
  const [copied, setCopied] = useState(false);
  const [busy, setBusy] = useState(false);
  const [linkState, setLinkState] = useState<"idle" | "busy" | "done" | "error">("idle");
  const [previewUrl, setPreviewUrl] = useState<string | null>(null); // rendered PNG awaiting save
  const [imgCopy, setImgCopy] = useState<"idle" | "done" | "fail">("idle");
  const previewRef = useRef<HTMLDivElement>(null);

  const allSel = items.length > 0 && sel.size === items.length;
  const selected = items.filter((x) => sel.has(x.i));
  // Too many bubbles → image would exceed canvas limits; block image share only.
  const overImgLimit = selected.length > IMAGE_SHARE_LIMIT;

  // What actually gets shared (link snapshot + exported image): the selected
  // text/media bubbles PLUS every tool-call block that falls within the selected
  // range — so a shared conversation reproduces the tool activity too, in order,
  // not just the prose.
  const shareItems = useMemo(() => {
    const selIdx = [...sel];
    if (selIdx.length === 0) return [];
    const lo = Math.min(...selIdx);
    const hi = Math.max(...selIdx);
    return messages
      .map((m, i) => ({ m, i }))
      .filter(({ m, i }) => (m.kind === "tools" ? i > lo && i < hi && (m.tools?.length ?? 0) > 0 : sel.has(i)));
  }, [messages, sel]);

  const toggle = (i: number) =>
    setSel((s) => {
      const n = new Set(s);
      if (n.has(i)) {
        n.delete(i);
      } else {
        n.add(i);
      }
      return n;
    });
  const toggleAll = () => setSel(allSel ? new Set() : new Set(items.map((x) => x.i)));

  const onCopy = async () => {
    const md = selected
      .map(({ m }) => `${m.role === "user" ? "You" : "Franklin"}: ${m.content || mediaTag(m)}`)
      .join("\n\n");
    if (await copyText(md)) {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  // Render the selected messages to a PNG and OPEN A PREVIEW — don't jump
  // straight to the system save dialog. The user then picks copy or download.
  const onExport = async () => {
    const node = previewRef.current;
    if (!node || selected.length === 0) return;
    setBusy(true);
    try {
      const bg = getComputedStyle(document.documentElement).getPropertyValue("--bg").trim() || "#ffffff";
      // Make sure fonts + any inline images are fully laid out/decoded before we
      // snapshot — otherwise the capture can be short or blank.
      try { await (document as Document & { fonts?: { ready: Promise<unknown> } }).fonts?.ready; } catch { /* noop */ }
      await Promise.all(
        Array.from(node.querySelectorAll("img")).map((img) =>
          img.complete ? Promise.resolve() : img.decode().catch(() => undefined),
        ),
      );
      // Full content size (not the clipped/visible box).
      const width = node.scrollWidth;
      const height = node.scrollHeight;
      // Browsers cap canvas dimensions (~16k px is safe across engines). A tall
      // chat × pixelRatio 2 easily blows past that and gets cropped — so scale
      // the ratio down to keep both axes under the limit. This is exactly why
      // long conversations were getting cut off.
      const MAX = 16000;
      const ratio = Math.max(1, Math.min(2, MAX / height, MAX / width));
      const dataUrl = await toPng(node, {
        pixelRatio: ratio,
        backgroundColor: bg,
        cacheBust: true,
        width,
        height,
        // Pin the clone's box to the full size so html-to-image doesn't inherit
        // any viewport-derived clipping.
        style: { width: `${width}px`, height: `${height}px` },
      });
      setPreviewUrl(dataUrl);
    } catch {
      /* ignore */
    } finally {
      setBusy(false);
    }
  };

  const onDownloadImg = () => {
    if (!previewUrl) return;
    const a = document.createElement("a");
    a.href = previewUrl;
    a.download = "franklin-chat.png";
    a.click();
  };

  const onCopyImg = async () => {
    if (!previewUrl) return;
    let ok = false;
    // 1) Electron's native image clipboard (navigator.clipboard image write is
    // flaky in Electron). If it's missing OR returns false, fall through.
    const bridge = (window as { __FRANKLIN__?: { copyImage?: (d: string) => boolean } }).__FRANKLIN__;
    if (bridge?.copyImage) {
      try { ok = bridge.copyImage(previewUrl); } catch { ok = false; }
    }
    // 2) Web ClipboardItem API (browser, or Electron without the bridge).
    if (!ok && navigator.clipboard && "write" in navigator.clipboard) {
      try {
        const blob = await (await fetch(previewUrl)).blob();
        await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
        ok = true;
      } catch {
        ok = false;
      }
    }
    setImgCopy(ok ? "done" : "fail");
    setTimeout(() => setImgCopy("idle"), 1800);
  };

  const onShareLink = async () => {
    if (selected.length === 0 || linkState === "busy") return;
    setLinkState("busy");
    try {
      // Snapshot the selected messages; only inline data: images travel (local
      // 127.0.0.1 media is stripped server-side anyway).
      const payload = {
        title: selected.find((x) => x.m.role === "user")?.m.content?.slice(0, 80) || "Franklin chat",
        messages: shareItems.map(({ m }) => ({
          role: m.role,
          content: m.content,
          kind: m.kind,
          image: m.image && m.image.startsWith("data:") ? m.image : undefined,
          // Tool-call activity travels too (label + what it was doing), so a
          // shared link reproduces the conversation faithfully.
          tools: m.kind === "tools" ? (m.tools ?? []).map((s) => ({ label: s.label, detail: s.detail })) : undefined,
        })),
      };
      const res = await fetch(SHARE_API, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const { url } = (await res.json()) as { url?: string };
      if (url && (await copyText(url))) {
        setLinkState("done");
        setTimeout(() => setLinkState("idle"), 2000);
      } else {
        throw new Error("no url");
      }
    } catch {
      setLinkState("error");
      setTimeout(() => setLinkState("idle"), 2000);
    }
  };

  const renderBubble = (m: ChatMessage, key: number | string) => {
    // Tool-call block — rendered exactly like the in-app collapsed ToolGroup
    // header (✓ · "Used N tools" · icon cluster), so the exported image matches
    // what's shown in the chat.
    if (m.kind === "tools") {
      const tools = m.tools ?? [];
      return (
        <div key={key} className="try-toolgroup">
          <div className="try-toolgroup-head">
            <span className="try-toolgroup-mark" aria-hidden><Check className="h-3.5 w-3.5" /></span>
            <span className="try-toolgroup-title">{t.activityUsed(tools.length)}</span>
            <span className="try-toolgroup-icons" aria-hidden>
              {tools.slice(0, 3).map((s, k) => (
                <span key={k} className="try-toolgroup-chip">{iconFor(s.label)}</span>
              ))}
            </span>
            <ChevronDown className="try-toolgroup-chevron h-4 w-4" aria-hidden />
          </div>
        </div>
      );
    }
    return (
    <div key={key} className={`try-msg try-msg-${m.role}`}>
      <div className="try-msg-role">{m.role === "user" ? "You" : "Franklin"}</div>
      {m.kind === "image" && m.image ? (
        <div className="try-msg-media"><img src={m.image} alt="" /></div>
      ) : m.kind === "video" && m.video ? (
        <div className="try-msg-media"><video src={m.video} controls /></div>
      ) : m.kind === "music" && m.music ? (
        <div className="try-msg-media try-msg-audio"><audio src={m.music} controls /></div>
      ) : (
        <div className="try-msg-body">
          {m.role === "assistant" ? <MessageContent content={m.content} /> : m.content}
        </div>
      )}
    </div>
    );
  };

  return (
    <div className="try-share-overlay" onClick={onClose} role="dialog" aria-modal="true">
      <div className="try-share-modal" onClick={(e) => e.stopPropagation()}>
        <div className="try-share-head">
          <span className="try-share-title">{L.title}</span>
          <button className="try-share-cancel" onClick={onClose}>{L.cancel}</button>
        </div>

        <div className="try-share-list">
          {items.map(({ m, i }) => (
            <button key={i} className={`try-share-item${sel.has(i) ? " is-on" : ""}`} onClick={() => toggle(i)}>
              <span className={`try-share-check${sel.has(i) ? " is-on" : ""}`}>{sel.has(i) && <Check className="h-3.5 w-3.5" />}</span>
              <div className="try-share-item-body">{renderBubble(m, i)}</div>
            </button>
          ))}
        </div>

        <div className="try-share-foot">
          <button className="try-share-all" onClick={toggleAll}>
            <span className={`try-share-check${allSel ? " is-on" : ""}`}>{allSel && <Check className="h-3.5 w-3.5" />}</span>
            {L.all}
          </button>
          <div className="try-share-actions">
            <button className="try-share-btn" onClick={onCopy} disabled={selected.length === 0}>
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? L.copied : L.copy}
            </button>
            <span title={overImgLimit ? L.imgLimit(IMAGE_SHARE_LIMIT) : undefined} style={{ display: "inline-flex" }}>
              <button
                className="try-share-btn"
                onClick={onExport}
                disabled={selected.length === 0 || busy || overImgLimit}
              >
                <ImageDown className="h-4 w-4" />
                {busy ? L.busy : L.img}
              </button>
            </span>
            <button
              className="try-share-btn is-primary"
              onClick={onShareLink}
              disabled={selected.length === 0 || linkState === "busy"}
            >
              {linkState === "done" ? <Check className="h-4 w-4" /> : <Link2 className="h-4 w-4" />}
              {linkState === "busy" ? L.linking : linkState === "done" ? L.linked : linkState === "error" ? L.linkErr : L.link}
            </button>
          </div>
        </div>
      </div>

      {/* Off-screen render target for the exported image. */}
      <div className="try-share-capture" aria-hidden>
        <div ref={previewRef} className="try-share-canvas">
          <div className="try-share-canvas-head">
            <div className="try-share-canvas-title">{L.heading}</div>
            <div className="try-share-canvas-meta">{fmtDate(lang)} · {L.disclaimer}</div>
          </div>
          <div className="try-share-canvas-rule" />
          {shareItems.map(({ m, i }) => renderBubble(m, `cap-${i}`))}
        </div>
      </div>

      {/* Image preview — shown BEFORE saving, so the user copies or downloads. */}
      {previewUrl && (
        <div className="try-imgpreview-overlay" onClick={() => setPreviewUrl(null)} role="dialog" aria-modal="true">
          <div className="try-imgpreview-modal" onClick={(e) => e.stopPropagation()}>
            <div className="try-share-head">
              <span className="try-share-title">{L.previewTitle}</span>
              <button className="try-imgpreview-x" onClick={() => setPreviewUrl(null)} aria-label={L.cancel}>
                <X className="h-[18px] w-[18px]" />
              </button>
            </div>
            <div className="try-imgpreview-body">
              <img className="try-imgpreview-img" src={previewUrl} alt="" />
            </div>
            <div className="try-imgpreview-foot">
              <button className="try-share-btn" onClick={onCopyImg}>
                {imgCopy === "done" ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                {imgCopy === "done" ? L.copiedImg : imgCopy === "fail" ? L.copyImgFail : L.copyImg}
              </button>
              <button className="try-share-btn is-primary" onClick={onDownloadImg}>
                <ImageDown className="h-4 w-4" />
                {L.download}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
